// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuGjF9RlZLyY78oC_kGR6O5t6IJdSdTAQ',
    appId: '1:105523236701:web:b43764325223458d0ee2b4',
    messagingSenderId: '105523236701',
    projectId: 'companyapp-d3ecd',
    authDomain: 'companyapp-d3ecd.firebaseapp.com',
    storageBucket: 'companyapp-d3ecd.appspot.com',
    measurementId: 'G-9G15CT8MTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6tKJuFTzKsgJei48Cq_tpg2nQcu_P6Z0',
    appId: '1:105523236701:android:8a27ccb4848f493b0ee2b4',
    messagingSenderId: '105523236701',
    projectId: 'companyapp-d3ecd',
    storageBucket: 'companyapp-d3ecd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBielnsOQtaIXbnT0_aShxrZvSUl695Z9E',
    appId: '1:105523236701:ios:8c4f751b1071a9910ee2b4',
    messagingSenderId: '105523236701',
    projectId: 'companyapp-d3ecd',
    storageBucket: 'companyapp-d3ecd.appspot.com',
    iosClientId: '105523236701-5vdclgqc18s7jvkshckhhcs75qam3l0d.apps.googleusercontent.com',
    iosBundleId: 'com.example.companyApp',
  );
}
